"use client";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { authenticatedFetch } from "../../lib/authenticatedFetch";
import styles from "./ProductGenerator.module.css";
type Tab="product"|"metafields"|"variants"|"images"|"seo"|"matrixify";
type Product={title:string;descriptionHtml:string;vendor:string;type:string;tags:string;categoryName:string;breadcrumbs:string;images:{url:string;alt:string;kind:string}[];variants:Record<string,string>[];metafields:{namespace:string;key:string;value:string;type:string}[];seo:{titleTag:string;descriptionTag:string;handle:string};gaps:string[]};
const examples=["https://www.hartmann-tresore.de/waffenschraenke/","https://www.burg-wachter.de/p/sejf/","https://www.chubbsafes.com/pl-pl/"]; const csv=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;
function tabText(p:Product,tab:Tab,rows:Record<string,string>[]){if(tab==="product")return `Tytuł: ${p.title}\nMarka: ${p.vendor}\nTyp: ${p.type}\nKategoria: ${p.categoryName}\nTagi: ${p.tags}\n\n${p.descriptionHtml}`;if(tab==="metafields")return p.metafields.map(x=>`${x.namespace}.${x.key} | ${x.type} | ${x.value}`).join("\n");if(tab==="variants")return JSON.stringify(p.variants,null,2);if(tab==="images")return p.images.map((x,i)=>`${i+1}. ${x.kind} | ${x.alt} | ${x.url}`).join("\n");if(tab==="seo")return `Title tag: ${p.seo.titleTag}\nMeta description: ${p.seo.descriptionTag}\nHandle: ${p.seo.handle}`;return JSON.stringify(rows,null,2)}
export default function Page(){const[urls,setUrls]=useState("");const[overrideName,setOverrideName]=useState("");const[technicalText,setTechnicalText]=useState("");const[pdfs,setPdfs]=useState<File[]>([]);const[products,setProducts]=useState<Product[]>([]);const[rows,setRows]=useState<Record<string,string>[]>([]);const[selected,setSelected]=useState(0);const[tab,setTab]=useState<Tab>("product");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[copied,setCopied]=useState(false);const p=products[selected];const urlCount=useMemo(()=>urls.split(/\r?\n/).filter(Boolean).length,[urls]);
function files(e:ChangeEvent<HTMLInputElement>){const next=Array.from(e.target.files??[]);if(next.some(x=>x.type!=="application/pdf"||x.size>10*1024*1024)){setError("Dodaj tylko pliki PDF do 10 MB.");return}setPdfs(next);}
async function generate(e:FormEvent){e.preventDefault();if(!urlCount||loading)return;setLoading(true);setError("");setProducts([]);const form=new FormData();form.set("urls",urls);form.set("overrideName",overrideName);form.set("technicalText",technicalText);pdfs.forEach(x=>form.append("pdfs",x));try{const r=await authenticatedFetch("/api/generator-produktow-shopify",{method:"POST",body:form});const d=await r.json().catch(()=>null) as {error?:string;products?:Product[];matrixifyRows?:Record<string,string>[]} | null;if(!r.ok||!d?.products||!d.matrixifyRows)throw new Error(d?.error||"Nie udało się wygenerować wierszy Matrixify.");setProducts(d.products);setRows(d.matrixifyRows);setSelected(0)}catch(x){setError(x instanceof Error?x.message:"Błąd generatora.")}finally{setLoading(false)}}
async function copy(){if(!p)return;await navigator.clipboard.writeText(tabText(p,tab,rows));setCopied(true);setTimeout(()=>setCopied(false),1500)}function download(format:"csv"|"xlsx"){const headers=Array.from(new Set(rows.flatMap(x=>Object.keys(x))));if(format==="csv"){const blob=new Blob([[headers.join(","),...rows.map(r=>headers.map(h=>csv(r[h])).join(","))].join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="matrixify-products.csv";a.click();URL.revokeObjectURL(a.href)}else{const sheet=XLSX.utils.json_to_sheet(rows,{header:headers});const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,"Products");XLSX.writeFile(book,"matrixify-products.xlsx")}}
return <main className={styles.page}><header><span>SHOPIFY + MATRIXIFY</span><h1>🛡️ Generator produktów Shopify</h1><p>Crawl URL-i, tekstowy odczyt PDF i importowe wiersze Matrixify.</p></header><form className={styles.card} onSubmit={generate}><label>URL produktu lub kategorii <small>jeden adres w linii, maks. 10</small><textarea value={urls} onChange={e=>setUrls(e.target.value)} placeholder="https://producent.pl/produkt/sejf"/></label><label>Pliki PDF <small>karty katalogowe i certyfikaty — odczyt wyłącznie tekstu</small><input type="file" accept="application/pdf,.pdf" multiple onChange={files}/>{pdfs.length>0&&<em>{pdfs.map(x=>x.name).join(", ")}</em>}</label><label>Nazwa/model <small>opcjonalne nadpisanie</small><input value={overrideName} onChange={e=>setOverrideName(e.target.value)}/></label><label>Dodatkowe dane techniczne <textarea value={technicalText} onChange={e=>setTechnicalText(e.target.value)} placeholder="Wklej specyfikację techniczną..."/></label><div className={styles.examples}>{examples.map(x=><button type="button" key={x} onClick={()=>setUrls(x)}>Przykład</button>)}<button className={styles.primary} disabled={!urlCount||loading}>{loading?"Crawluję, czytam PDF i tworzę Matrixify…":"Wygeneruj wiersz Matrixify"}</button></div></form>{error&&<p className={styles.error}>{error}</p>}{p&&<section className={styles.result}><div className={styles.productSwitch}>{products.map((x,i)=><button key={`${x.title}-${i}`} className={i===selected?styles.active:""} onClick={()=>setSelected(i)}>{x.title}</button>)}<button onClick={()=>download("xlsx")}>⬇ XLSX</button><button onClick={()=>download("csv")}>⬇ CSV</button></div><div className={styles.tabs}>{([['product','Dane produktu'],['metafields','Metapola'],['variants','Warianty'],['images','Zdjęcia i rysunki'],['seo','SEO listing'],['matrixify','Podgląd Matrixify']] as [Tab,string][]).map(([id,l])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{l}</button>)}<button onClick={()=>void copy()}>{copied?"✓ Skopiowano":"📋 Kopiuj"}</button></div><pre>{tabText(p,tab,rows)}</pre>{p.gaps.length>0&&<p className={styles.gaps}>Braki źródłowe: {p.gaps.join(" · ")}</p>}</section>}</main>}
