"use client";

import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { authenticatedFetch } from "../../lib/authenticatedFetch";
import styles from "./ProductGenerator.module.css";

type Product = { sourceUrl: string; title: string; descriptionHtml: string; categoryPath: string; breadcrumbs: string; images: string[]; price: string; variants: Array<{ option: string; values: string[]; suffix: string }>; metafields: Array<{ name: string; value: string }>; proposedMetafields: Array<{ name: string; type: string; namespaceKey: string; reason: string }>; seo: { pageTitle: string; metaDescription: string; handle: string }; sourceGaps: string[] };
type Tab = "content" | "metafields" | "variants" | "seo";
const examples = ["https://www.hartmann-tresore.de/waffenschraenke/", "https://www.burg-wachter.de/p/sejf/", "https://www.chubbsafes.com/pl-pl/"];
const csv = (v: string) => `"${v.replaceAll('"', '""')}"`;

function section(product: Product, tab: Tab) {
  if (tab === "content") return `Tytuł: ${product.title}\n\nKategoria: ${product.categoryPath}\n\n${product.descriptionHtml}\n\nŹródło: ${product.sourceUrl}`;
  if (tab === "metafields") return [...product.metafields.map((x) => `${x.name}: ${x.value}`), ...product.proposedMetafields.map((x) => `PROPONOWANE | ${x.name} | ${x.type} | ${x.namespaceKey} | ${x.reason}`)].join("\n");
  if (tab === "variants") return product.variants.map((x) => `${x.option} | ${x.values.join(", ")} | SKU suffix: ${x.suffix}`).join("\n") || "brak danych – do uzupełnienia";
  return `Tytuł strony: ${product.seo.pageTitle}\nMeta opis: ${product.seo.metaDescription}\nHandle: ${product.seo.handle}`;
}

export default function ShopifyProductGeneratorPage() {
  const [urls, setUrls] = useState(""); const [overrideName, setOverrideName] = useState(""); const [technicalText, setTechnicalText] = useState(""); const [fileName, setFileName] = useState(""); const [products, setProducts] = useState<Product[]>([]); const [selected, setSelected] = useState(0); const [tab, setTab] = useState<Tab>("content"); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  const urlList = useMemo(() => urls.split(/\r?\n/).map((x) => x.trim()).filter(Boolean), [urls]);
  const product = products[selected];
  async function loadFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (file.size > 5 * 1024 * 1024) { setError("Plik może mieć maksymalnie 5 MB."); return; } setFileName(file.name); const content = await file.text(); setTechnicalText(content.slice(0, 20_000)); }
  async function generate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!urlList.length || loading) return; setLoading(true); setError(""); setProducts([]); try { const response = await authenticatedFetch("/api/generator-produktow-shopify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ urls: urlList, overrideName, technicalText }) }); const data = await response.json().catch(() => null) as { error?: string; products?: Product[] } | null; if (!response.ok || !data?.products) throw new Error(data?.error || "Nie udało się wygenerować produktów."); setProducts(data.products); setSelected(0); } catch (e) { setError(e instanceof Error ? e.message : "Nie udało się wygenerować produktów."); } finally { setLoading(false); } }
  async function copy() { if (!product) return; await navigator.clipboard.writeText(section(product, tab)); setCopied(true); setTimeout(() => setCopied(false), 1800); }
  function exportCsv() { const rows = ["Handle,Title,Body HTML,Vendor,Type,Tags,Option1 Name,Option1 Value,Variant SKU,Variant Price,SEO Title,SEO Description,Image Src"]; for (const p of products) { const variants = p.variants.length ? p.variants : [{ option: "Title", values: ["Default Title"], suffix: "" }]; variants.forEach((v) => v.values.forEach((value) => rows.push([p.seo.handle.replace(/^products\//, ""), p.title, p.descriptionHtml, "", p.categoryPath, p.breadcrumbs, v.option, value, v.suffix, p.price, p.seo.pageTitle, p.seo.metaDescription, p.images[0] || ""].map(csv).join(",")))); } const blob = new Blob([rows.join("\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "shopify-matrixify-products.csv"; link.click(); URL.revokeObjectURL(link.href); }
  return <main className={styles.page}><header><span>SHOPIFY + RESEARCH</span><h1>🛡️ Generator produktów Shopify</h1><p>Crawl producenta, dane techniczne i gotowa karta do Matrixify.</p></header><form className={styles.card} onSubmit={generate}><label>URL produktu lub kategorii <small>jeden link w linii</small><textarea value={urls} onChange={(e) => setUrls(e.target.value)} placeholder="https://producent.pl/produkt/sejf..." /></label><label>Nazwa/model produktu <small>opcjonalnie — nadpisuje tytuł źródłowy</small><input value={overrideName} onChange={(e) => setOverrideName(e.target.value)} /></label><label>Dane techniczne <small>wklej tekst lub dodaj kartę katalogową (PDF/TXT do 5 MB)</small><textarea value={technicalText} onChange={(e) => setTechnicalText(e.target.value)} placeholder="Wymiary, waga, klasa, rodzaj zamka..." /><input type="file" accept=".pdf,.txt,text/plain,application/pdf" onChange={loadFile} />{fileName && <em>Załączono: {fileName}</em>}</label><div className={styles.examples}>{examples.map((x) => <button key={x} type="button" onClick={() => setUrls(x)} disabled={loading}>Przykładowy URL</button>)}<button className={styles.primary} disabled={!urlList.length || loading}>{loading ? "Crawluję i generuję…" : "Wygeneruj treść produktu"}</button></div></form>{error && <p className={styles.error}>{error}</p>}{product && <section className={styles.result}><div className={styles.productSwitch}>{products.map((p, i) => <button key={`${p.title}-${i}`} className={i === selected ? styles.active : ""} onClick={() => setSelected(i)}>{p.title}</button>)}<button onClick={exportCsv}>⬇ Eksport CSV Matrixify</button></div><div className={styles.tabs}>{([['content','Tytuł i opis'],['metafields','Metapola'],['variants','Warianty'],['seo','SEO listing']] as [Tab,string][]).map(([id,label]) => <button key={id} className={tab === id ? styles.active : ""} onClick={() => setTab(id)}>{label}</button>)}<button onClick={() => void copy()}>{copied ? "✓ Skopiowano" : "📋 Kopiuj"}</button></div><pre>{section(product, tab)}</pre>{product.sourceGaps?.length > 0 && <p className={styles.gaps}>Braki źródłowe: {product.sourceGaps.join(" · ")}</p>}</section>}</main>;
}
